version: 2

build:
  image: latest

sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt