# Note on this extension: in the future, this set may be captured by "single cell library construction" from EFO, but
# for the recent past that term contained Visium transcriptomics and a few non-single-cell resolved assays.

EFO_TERMS = {
    "sfaira single cell library construction": [
        "10x 3' transcription profiling",
        "10x 3' v1",
        "10x 3' v2",
        "10x 3' v3",
        "10x 5' transcription profiling",
        "10x 5' v1",
        "10x 5' v2",
        "10x Ig enrichment",
        "10x TCR enrichment",
        "10x feature barcode (CRISPR screening)",
        "10x feature barcode (cell surface protein profiling)",
        "10x feature barcode (sample multiplexing)",
        "10x feature profiling",
        "10x immune profiling",
        "10x multiome",
        "10x scATAC-seq",
        "CEL-seq",
        "CEL-seq2",
        "CITE-seq",
        "CITE-seq (cell surface protein profiling)",
        "CITE-seq (sample multiplexing)",
        "DroNc-seq",
        "Drop-seq",
        "Fluidigm C1-based library preparation",
        "MARS-seq",
        "Nx1-seq",
        "Quartz-seq",
        "SCRB-seq",
        "SORT-seq",
        "SPLiT-seq",
        "STRT-seq",
        "Seq-Well",
        "Seq-Well S3",
        "Smart-like",
        "Smart-seq",
        "Smart-seq2",
        "barcoded plate-based single cell RNA-seq",
        "cell hashing",
        "comparative genomic hybridization (CGH)",
        "droplet-based single-cell RNA library preparation",
        "inDrop",
        "mCT-seq",
        "mcSCRB-seq",
        "microwell-seq",
        "scATAC-seq",
        "scATAC-seq (Microfluidics)",
        "scATAC-seq (cell index)",
        "scBS-seq",
        "scChIP-seq",
        "sci-CAR",
        "sci-Plex",
        "sci-RNA-seq",
        "sci-RNA-seq3",
        "single cell Hi-C",
        "snmC-Seq2",
    ],
}
