from .external import CelltypeVersionsBase

CELLTYPES_HUMAN_KIDNEY_V0 = [
    ['Acinar cell', "nan"],
    ['Antigen presenting cell (RPS high)', "nan"],
    ['B cell', "nan"],
    ['B cell (Plasmocyte)', "nan"],
    ['CB CD34+', "nan"],
    ['CD4 T cell', "nan"],
    ['CD8 T cell', "nan"],
    ['CNT/PC - proximal UB', "nan"],
    ['Cap mesenchyme', "nan"],
    ['Chondrocyte', "nan"],
    ['Collecting Duct - Intercalated Cells Type A (cortex)', "nan"],
    ['Collecting Duct - Intercalated Cells Type A (medulla)', "nan"],
    ['Collecting Duct - Intercalated Cells Type B', "nan"],
    ['Collecting Duct - PCs - Stressed Dissoc Subset', "nan"],
    ['Collecting Duct - Principal Cells (cortex)', "nan"],
    ['Collecting Duct - Principal Cells (medulla)', "nan"],
    ['Connecting tubule', "nan"],
    ['Decending Limb', "nan"],
    ['Distal Convoluted Tubule', "nan"],
    ['Distal S shaped body', "nan"],
    ['Distal renal vesicle', "nan"],
    ['Distinct proximal tubule 1', "nan"],
    ['Distinct proximal tubule 2', "nan"],
    ['Endocrine cell', "nan"],
    ['Endothelial Cells (unassigned)', "nan"],
    ['Endothelial Cells - AEA & DVR', "nan"],
    ['Endothelial Cells - AVR', "nan"],
    ['Endothelial Cells - glomerular capillaries', "nan"],
    ['Endothelial cell (APC)', "nan"],
    ['Endothelial cell (endothelial to mesenchymal transition)', "nan"],
    ['Enterocyte ', "nan"],
    ['Enterocyte progenitor', "nan"],
    ['Epithelial Cells (unassigned)', "nan"],
    ['Epithelial progenitor', "nan"],
    ['Erythroid', "nan"],
    ['Erythroid progenitor cell (RP high)', "nan"],
    ['Fasciculata cell', "nan"],
    ['Fibroblast', "nan"],
    ['Gastric endocrine cell', "nan"],
    ['Goblet cell', "nan"],
    ['Indistinct intercalated cell', "nan"],
    ['Innate like lymphocyte', "nan"],
    ['Intermediated cell', "nan"],
    ['Interstitium', "nan"],
    ['Loop of Henle', "nan"],
    ['M2 Macrophage', "nan"],
    ['MNP-a/classical monocyte derived', "nan"],
    ['MNP-b/non-classical monocyte derived', "nan"],
    ['MNP-c/dendritic cell', "nan"],
    ['MNP-d/Tissue macrophage', "nan"],
    ['Macrophage', "nan"],
    ['Mast cell', "nan"],
    ['Mast cells', "nan"],
    ['Medial S shaped body', "nan"],
    ['Megakaryocyte', "nan"],
    ['Mesangial Cells', "nan"],
    ['Monocyte', "nan"],
    ['Myeloid cell', "nan"],
    ['Myofibroblast', "nan"],
    ['NK cell', "nan"],
    ['NKT cell', "nan"],
    ['Neuron', "nan"],
    ['Neutrophil', "nan"],
    ['Neutrophil (RPS high)', "nan"],
    ['Pelvic epithelium', "nan"],
    ['Pelvic epithelium - distal UB', "nan"],
    ['Peritubular capillary endothelium 1', "nan"],
    ['Peritubular capillary endothelium 2', "nan"],
    ['Plasmacytoid dendritic cell', "nan"],
    ['Podocyte', "nan"],
    ['Primordial germ cell', "nan"],
    ['Proliferating B cell', "nan"],
    ['Proliferating NK cell', "nan"],
    ['Proliferating Proximal Tubule', "nan"],
    ['Proliferating T cell', "nan"],
    ['Proliferating cDC2', "nan"],
    ['Proliferating cap mesenchyme', "nan"],
    ['Proliferating distal renal vesicle', "nan"],
    ['Proliferating fibroblast', "nan"],
    ['Proliferating macrophage', "nan"],
    ['Proliferating monocyte', "nan"],
    ['Proliferating myofibroblast', "nan"],
    ['Proliferating stroma progenitor', "nan"],
    ['Proximal S shaped body', "nan"],
    ['Proximal Tubule Epithelial Cells (S1)', "nan"],
    ['Proximal Tubule Epithelial Cells (S2)', "nan"],
    ['Proximal Tubule Epithelial Cells (S3)', "nan"],
    ['Proximal Tubule Epithelial Cells - Fibrinogen+ (S3)', "nan"],
    ['Proximal Tubule Epithelial Cells - Stress/Inflam', "nan"],
    ['Proximal UB', "nan"],
    ['Proximal renal vesicle', "nan"],
    ['Proximal tubule progenitor', "nan"],
    ['Sinusoidal endothelial cell', "nan"],
    ['Skeletal muscle cell', "nan"],
    ['Stratified epithelial cell', "nan"],
    ['Stroma progenitor', "nan"],
    ['Stromal cell', "nan"],
    ['Thick ascending limb of Loop of Henle', "nan"],
    ['Thin ascending limb', "nan"],
    ['Transitional urothelium', "nan"],
    ['Unknown - Novel PT CFH+ Subpopulation (S2)', "nan"],
    ['Vascular Smooth Muscle Cells and pericytes', "nan"],
    ['cDC1', "nan"],
    ['cDC2', "nan"],
    ['hESC', "nan"],
    ['pDC', "nan"]
]
ONTOLOGIES_HUMAN_KIDNEY_V0 = {
    "names": {
        'Type A intercalated cell': ['Collecting Duct - Intercalated Cells Type A (cortex)',
                                         'Collecting Duct - Intercalated Cells Type A (medulla)'],
        'Principal cell': ['Collecting Duct - PCs - Stressed Dissoc Subset',
                           'Collecting Duct - Principal Cells (cortex)',
                           'Collecting Duct - Principal Cells (medulla)'],
        'Proximal tubule': ['Proximal Tubule Epithelial Cells (S1)',
                            'Proximal Tubule Epithelial Cells (S2)',
                            'Proximal Tubule Epithelial Cells (S3)',
                            'Proximal Tubule Epithelial Cells - Fibrinogen+ (S3)',
                            'Proximal Tubule Epithelial Cells - Stress/Inflam'],
        'Dendritic cell': ['MNP-c/dendritic cell', 'Plasmacytoid dendritic cell'],
        'Endothelial cell': ['Endothelial Cells (unassigned)', 'Endothelial Cells - AEA & DVR', 'Endothelial Cells - AVR', 'Endothelial Cells - glomerular capillaries', 'Peritubular capillary endothelium 1', 'Peritubular capillary endothelium 2'],
        'Epithelial cell': ['Pelvic epithelium', 'Pelvic epithelium - distal UB', 'Proximal Tubule Epithelial Cells (S1)', 'Proximal Tubule Epithelial Cells (S2)', 'Proximal Tubule Epithelial Cells (S3)', 'Proximal Tubule Epithelial Cells - Fibrinogen+ (S3)', 'Proximal Tubule Epithelial Cells - Stress/Inflam'],
        'Intercalated cell': ['Collecting Duct - Intercalated Cells Type A (cortex)', 'Collecting Duct - Intercalated Cells Type A (medulla)', 'Collecting Duct - Intercalated Cells Type B', 'Indistinct intercalated cell'],
        'T cell': ['CD4 T cell', 'CD8 T cell'],
        'Ureteric bud cell': ['CNT/PC - proximal UB', 'Proximal UB', 'Pelvic epithelium - distal UB']
    },
    "ontology_ids": {},
}


class CelltypeVersionsHumanKidney(CelltypeVersionsBase):

    def __init__(self, **kwargs):
        self.celltype_universe = {
            "0": CELLTYPES_HUMAN_KIDNEY_V0
        }
        self.ontology = {
            "0": ONTOLOGIES_HUMAN_KIDNEY_V0
        }
        super(CelltypeVersionsHumanKidney, self).__init__(**kwargs)
