name: Create sfaira data-loader templates

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.7, 3.8]
    env:
      PYTHONIOENCODING: utf-8

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade and install pip
        run: python -m pip install --upgrade pip

      - name: Build sfaira
        run: pip install .

      - name: Create single_dataset template
        run: |
          cd ..
          echo -e "\n\n\n\n\n\n\n\n\n\n\n" | sfaira create-dataloader
          rm -rf d10_1000_j_journal_2021_01_001/

      - name: Create multiple_datasets_single_file template
        run: |
          cd ..
          echo -e "\033[B\n\n\n\n\n\n\n\n\n\n\n" | sfaira create-dataloader
          rm -rf d10_1000_j_journal_2021_01_001/

      - name: Create multiple_datasets_streamlined template
        run: |
          cd ..
          echo -e "\033[B\n\033[B\n\n\n\n\n\n\n\n\n\n" | sfaira create-dataloader
          rm -rf d10_1000_j_journal_2021_01_001/

      - name: Create multiple_datasets_not_streamlined template
        run: |
          cd ..
          echo -e "\033[B\n\033[B\n\033[B\n\n\n\n\n\n\n\n\n" | sfaira create-dataloader
          rm -rf d10_1000_j_journal_2021_01_001/
