name: Create sfaira data-loader templates

on: [push, pull_request]

jobs:
  create-templates:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      PYTHONIOENCODING: utf-8

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8

      - name: Upgrade and install pip and wheel
        run: python -m pip install --upgrade pip wheel

      - name: Build sfaira
        run: pip install .

      - name: Create single_dataset template
        run: |
          mkdir -p ./d10_1000_j_journal_2022_01_001
          echo -e "\nEinstein, Albert\n1\nX_umap\n10.1000/j.journal.2022.01.001\nURL\nURL2\nY2022\nX\n\n\n\n\n\n\n\n\n\n\n\n\nHomo sapiens\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nindex\n\n" | sfaira create-dataloader
          sfaira validate-dataloader --doi 10.1000/j.journal.2022.01.001
          rm -rf ./d10_1000_j_journal_2022_01_001
